basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: hi@syakod.com
    name: syakod
    url: https://github.com/carot-admin
  description: carot-admin 是基于 gin、JWT 和 RBAC 的 go 后台管理系统
  license:
    name: MIT
    url: https://github.com/syakod/carot-admin/blob/main/LICENSE
  termsOfService: https://github.com/syakod
  title: carot-admin 后端 API 文档
  version: 1.0.0
paths:
  /hello:
    get:
      responses: {}
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
